name: Publish
on:
  release:
    types: [published]
  push:
    branches:
      - develop
      - 'release/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: npm run publish:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}